import { GrTwitter } from 'react-icons/gr';
export const data = [
  {
    id: 1,
    img: require("./assets/Home/Thumbnails/download.jpg"),
    video: require("./assets/Home/Videos/1_Grow_up_Stage_Modul_video.mp4"),
    title : "Grow up",
    subtitle : "Stories of a new generation",
  },
  {
    id: 2,
    img: require("./assets/Home/Thumbnails/download-1.jpg"),
    video: require("./assets/Home/Videos/IAA_Makingof_8Sec_L.mp4"),
    title : "Luxury in motion",
    subtitle : "The FO15 concept car",
  },
  {
    id: 3,
    img: require("./assets/Home/Thumbnails/download-2.jpg"),
    video: require("./assets/Home/Videos/TimeToLookUpAgain_8Sec_L.mp4"),
    title : "Unleash your senses",
    subtitle : "The new C-Class cabriolet",
  },
  {
    id: 4,
    img: require("./assets/Home/Thumbnails/download-3.jpg"),
    video: require("./assets/Home/Videos/EasyRider_8Sec_L.mp4"),
    title : "Easy Driver",
    subtitle : "Mercedes AMG GT C Roadster",
  },
  {
    id: 5,
    img: require("./assets/Home/Thumbnails/download-4.jpg"),
    video: require("./assets/Home/Videos/katjes_stage-1.mp4"),
    title : "Jes! All veggie",
    subtitle : "Our first ever sweets campaign",
  },
  {
    id: 6,
    img: require("./assets/Home/Thumbnails/download-5.jpg"),
    video: require("./assets/Home/Videos/risk_1.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 7,
    img: require("./assets/Home/Thumbnails/download-6.jpg"),
    video: require("./assets/Home/Videos/Mercedes_Leon_stage.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 8,
    img: require("./assets/Home/Thumbnails/download-7.jpg"),
    video: require("./assets/Home/Videos/stage_xmas.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 9,
    img: require("./assets/Home/Thumbnails/download-8.jpg"),
    video: require("./assets/Home/Videos/F1_stage-1.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 10,
    img: require("./assets/Home/Thumbnails/download-9.jpg"),
    video: require("./assets/Home/Videos/eq_stage_video.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 11,
    img: require("./assets/Home/Thumbnails/download-10.jpg"),
    video: require("./assets/Home/Videos/eq_stage_video.mp4"),
    title : "",
    subtitle : "",
  },
  {
    id: 12,
    img: require("./assets/Home/Thumbnails/download-11.jpg"),
    video: require("./assets/Home/Videos/stage_g_class_dna.mp4"),
    title : "Stronger than time",
    subtitle : "The new G-Class",
  },
];
